// <auto-generated />
using System;
using LibraryCoreProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibraryCoreProject.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20220107140412_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryCoreProject.Models.Book", b =>
                {
                    b.Property<string>("Bookcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bookname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("catid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("rate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Bookcode");

                    b.HasIndex("catid");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryCoreProject.Models.Category", b =>
                {
                    b.Property<string>("catid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Categoryname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("catid");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LibraryCoreProject.Models.Book", b =>
                {
                    b.HasOne("LibraryCoreProject.Models.Category", "Category")
                        .WithMany("Book")
                        .HasForeignKey("catid");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LibraryCoreProject.Models.Category", b =>
                {
                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
